Repository betagouv/leximpact-server, pull requests merged in 2019-06, with the labels that each got.

#22 Merge d'intégration pour passer l'API sur master
  Procfile
  Simulation_engine/simulate_pop_from_reform.py
  interface_reform/app.py
  server/app.py
  setup.py
Labels: kind:refactoring, type:api

#21 Déprécie la version Dash
  Simulation_engine/simulate_pop_from_reform.py
  interface_reform/__init__.py
  interface_reform/app.py
  interface_reform/assets/ImagesCasTypes/CT1-celibataireSMIC.png
  interface_reform/assets/ImagesCasTypes/CT2-Couple2enfants.png
  interface_reform/assets/ImagesCasTypes/CT3-Couple2enfantsOutremer.png
  interface_reform/assets/ImagesCasTypes/CT4-CoupleRetraite.png
  interface_reform/assets/ImagesCasTypes/CT5-ParentIsole.png
  interface_reform/assets/ImagesCasTypes/CT6-Famille10000euros.png
  interface_reform/assets/favicon.ico
  interface_reform/components/__init__.py
  interface_reform/components/article.py
  interface_reform/components/graph_cas_type.py
  interface_reform/components/header.py
  server/handlers/cas_types.py
  setup.py
  tests/interface_reform/components/test_article.py
  tests/interface_reform/components/test_graph_cas_type.py
  tests/interface_reform/components/test_header.py
Labels: kind:refactoring, type:client

#23 Merge d'intégration des dernières évolututions
  Simulation_engine/DCT.csv
  Simulation_engine/simulate_pop_from_reform.py
  server/api.yaml
  server/handlers/cas_types.py
  setup.py
Labels: kind:solution, type:api

#24 Ajouté un server de production
  .editorconfig
  Makefile
  Procfile
  README.md
  Simulation_engine/simulate_pop_from_reform.py
  server/api.yaml
  server/app.py
  server/handlers/__init__.py
  server/handlers/cas_types.py
  server/handlers/welcome.py
  server/services/__init__.py
  server/services/openfisca.py
  setup.cfg
  setup.py
  tests/server/handlers/conftest.py
  tests/server/handlers/test_cas_types.py
  tests/server/handlers/test_welcome.py
  tests/server/stress/benchmark.sh
  tests/server/stress/payload.json
  tests/server/stress/server.sh
  tests/server/stress/test.sh
Labels: kind:devops, type:api

#27 Ajoute de l'intégration en continu
  .buildpacks
  .circleci/config.yml
  Aptfile
  setup.cfg
  setup.py
Labels: kind:devops, type:api, type:engine
